name: ssocks # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: shadowsocks # 79 char long summary
description: |
  This is a shadowsocks snap app

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  ssocks: 
    command: bin/wrapper
    plugs: [network,home]

parts:
  ss:
    plugin: go
    source: https://github.com/shadowsocks/shadowsocks-go
    source-type: git
  config:
    plugin: dump
    source: .
    organize:
      config.json: bin/config.json
      wrapper: bin/wrapper
      configure: meta/hooks/configure
