#!/bin/sh
set -e

config_file="$SNAP_DATA/config.json"  

if [ -f "$config_file" ]  

then  
    cat $config_file 
    $SNAP/bin/shadowsocks-local -c $config_file
else  
    echo "$config_file not found."  
    echo "Please run the following commmand to generate the file:"  
    echo "sudo snap set ssocks server=127.0.0.1 serverport=12255 localport=7777 password=123456 method=aes-128-cfb timeout=600"
    echo "you can set only the parts which the above default values do not work for you!"
    echo "Typically, you would use \"sudo snap set ssocks server=127.0.0.1 password=123456\""
fi

